material-components/material-components-ios

components/NavigationBar/src/MDCNavigationBar.m
Addresses bug where navigation bar title is not aligned correctly in RTL languages since MDCRectFlippedForRTL is called twice (for both vertical and horizontal alignment). MDCRectFlippedForRTL should only be called once.
Fixes issue: https://github.com/material-components/material-components-ios/issues/1099
=> Remove redundant RTL frame adjustment

README.md
[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.
=> Add Travis CI build badge to README.md

.travis.yml
This won't do anything yet, but once we start emitting code coverage files it will.
Related to #1113
=> Add uploading of testing code coverage results to codecov.io

components/AppBar/src/MDCAppBar.m
Since the header stack view is going to be laid out with auto layout, it should be inited with a CGRectZero. Doing it with self.view.bounds creates a tiny loop since the view is not loaded yet.
[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.
=> [AppBar] Header stack view in AppBarController

catalog/MDCCatalog/MDCCatalogComponentsController.swift, components/Ink/src/MDCInkTouchController.h, demos/Shrine/Shrine/ShrineInkOverlay.swift
This PR changes the `MDCInkTouchController` initializer from `nullable` to `nonnull`. The catalog needed a trivial update to work with this change, but otherwise this should be fine.
Closes #430.
=> [Ink] Add nonnull to the MDCInkTouchController initializer

components/Buttons/examples/ButtonsStoryboardAndProgrammatic.swift, components/Buttons/examples/resources/ButtonsStoryboardAndProgrammatic.storyboard
This PR vertically and horizontally centers the buttons in the `Buttons (Swift and Storyboard)` catalog demo.
The technique here was to have two container views to represent the left and right halves of the screen, and then an inner container view for each which vertically and horizontally centers the buttons. An alternative approach could be to have the one container view for each button group, and then use a stack view to handle the distribution.
Also, should the `Storyboard` label be white? That existed before these changes, but I think it is intended to match the `Programmatic` label.
Closes #378.
---
**Landscape:**
**Portrait:**
=> [Catalog] Center views in the Buttons (Swift and Storyboard) demo

catalog/MDCCatalog.xcodeproj/project.pbxproj
This PR fixes an issue where interaction tests would fail immediately when running on iOS 8.0.
The solution was to change the interaction test deployment target from 9.3 back to 8.0. After this change, the tests pass locally on 8.1, 9.3, and 10.2.
Closes #1038.
=> [Tests] Fix test failures on iOS 8

catalog/MDCCatalog/MDCCatalogComponentsController.swift
This PR turns the `inkController` property into a `lazy var`, so it no longer needs to be referenced as an optional.
Closes #1125.
=> [Catalog] Clean up an optional in MDCCatalogComponentsController

components/Snackbar/src/private/MDCSnackbarMessageView.m
=> [Snackbar] Render messages correctly for RTL

components/FlexibleHeader/tests/unit/FlexibleHeaderViewControllerTopLayoutGuideTests.m
This closes issue [1040](https://github.com/material-components/material-components-ios/issues/1040)
Changes: Update content size in test so it is not nil width
=> [FlexibleHeader] - Update tests so as not to have 0 in contentSize

.swiftlint.yml, catalog/MDCCatalog/AppDelegate.swift, catalog/MDCCatalog/MDCCatalogComponentsController.swift, catalog/MDCCatalog/MDCCatalogTileView.swift, catalog/MDCCatalog/MDCNodeListViewController.swift
=> Fix SwiftLint warnings

components/Collections/examples/CollectionsStoryboardExample.m, components/Collections/examples/resources/CollectionsStoryboardExample.storyboard
Added an example for [this StackOverflow question](http://stackoverflow.com/questions/41382383/is-it-possible-to-set-mdccollectionviewcell-from-interface-builder). It uses a custom cell with italic text and a light blue background created in a Storyboard.
=> [Collections] Added custom Storyboard cell to the Storyboard example.

components/FeatureHighlight/examples/supplemental/FeatureHighlightExampleSupplemental.m, components/FeatureHighlight/src/MDCFeatureHighlightViewController.h, components/FeatureHighlight/src/private/MDCFeatureHighlightView.m
This does not have an upper limit so it does let people create absurd looking highlights. We should eventually support highlights without the white inner highlight for cases where the content is particularly large. Closes #860.
Before:
After:
=> [Feature highlight] Dynamically size inner highlight

components/AppBar/examples/AppBarModalPresentationExample.m, components/AppBar/examples/AppBarModalPresentationExample.swift
Changes Made:
- Added example to MDCCatalog to display modal presentation of form sheet while using MDCAppBar
- Added example to MDCCatalog to display modal presentation of form sheet while using MDCAppBar using Swift
This PR will display [issue 1105](https://github.com/material-components/material-components-ios/issues/1105) with which to make proposed fixes indicated in [the design doc](https://docs.google.com/document/d/1OtDBWyOb3G6p8v9vDK6cGf5P82JSH7RUi-MIrtxcajY/edit).
=> [AppBar] - Added Modal Presentation App Bar Example

README.md
The first time I was looking at the code, I couldn't find the source of the components, until @willlarche pointed it to me how to find it. This PR adds a line to make it more explicit where the code can be find.
=> Explains where to find the development code

components/Snackbar/src/private/MDCSnackbarOverlayView.m
This PR fixes the glitchy snackbar animation by holding on to each animation after it is completed. 
Tested on device with rotation.
Closes #1018.
=> [Snackbar] Fix glitchy snackbar dismissal animation

components/Snackbar/src/private/MDCSnackbarOverlayView.m
Reverts material-components/material-components-ios#1161
Original PR breaks Snackbar Overlay View sample.
=> Revert "[Snackbar] Fix glitchy snackbar dismissal animation"

components/Snackbar/src/MDCSnackbarMessageView.m
Prior to this change, one needed to add `components/Snackbar/src/private` to the list of `include_dirs`.
Closes #1167.
[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.
=> [Snackbar] Update file path for private file.

components/Snackbar/src/private/MDCSnackbarOverlayView.m
Fixes the glitchy snackbar dismissal animation. Tested with rotation and MDCOverlayObserver on device.
This very slightly changes the behavior of MDCOverlayObserver by returning an offscreen rect instead of CGRectNull when the snackbar disappears.
Closes #1018
=> [Snackbar] Fix glitchy dismissal animation

CHANGELOG.md, MaterialComponents.podspec, MaterialComponentsCatalog.podspec, MaterialComponentsUnitTests.podspec, catalog/Podfile.lock, demos/Bare/Podfile.lock, demos/Pesto/Podfile.lock, demos/Shrine/Podfile.lock, demos/supplemental/RemoteImageServiceForMDCDemos.podspec
Update podspec files to require a minimum of iOS 8.0 as a deployment target.
We will no longer support devices on iOS 7 or earlier.
=> Update minimum deployment target to iOS 8.0

components/Dialogs/src/MDCAlertController.m
We were using black for the alert body text.
We are now using black with the proper opacity.
From the Spec
Alert:
https://material.io/guidelines/components/dialogs.html#dialogs-behavior
Color:
https://material.io/guidelines/components/text-fields.html#text-fields-labels
=> [Dialogs] Alert body text color to match spec

catalog/Podfile.lock, components/Typography/examples/TypographyMaterialStylesViewController.h, components/Typography/examples/TypographyMaterialStylesViewController.m, components/Typography/src/MDCFontTextStyle.h, components/Typography/src/MaterialTypography.h, components/Typography/src/UIFont+MaterialTypography.h, components/Typography/src/UIFont+MaterialTypography.m, components/Typography/src/UIFontDescriptor+MaterialTypography.h, components/Typography/src/UIFontDescriptor+MaterialTypography.m, components/Typography/src/private/MDCFontTraits.h, components/Typography/src/private/MDCFontTraits.m, components/Typography/src/private/UIFont+MaterialTypographyPrivate.h, components/Typography/src/private/UIFont+MaterialTypographyPrivate.m
This adds the interface and implementation for MDCFontTextStyle.
This API was originally reviewed in #1170.
=> [Typography] Initial Material Text Style API

components/NavigationBar/README.md
Was using the docs and ran into a spelling issue in the example include. Fixed.
=> [NavigationBar] Fix spelling for MaterialNavigationBar.h in include statement.

demos/Bare/Bare/AppDelegate.h
* The app delegate must implement the window property if it wants to use a main storyboard file.
* src: http://stackoverflow.com/a/32157899/3670829
=> [demos/Bare] Fix runtime initialization error 

components/Buttons/src/MDCButton.m
This PR reverts the changes in https://github.com/material-components/material-components-ios/pull/1134 due to side effects that it causes. See https://github.com/material-components/material-components-ios/issues/1195 and https://github.com/material-components/material-components-ios/issues/1160 for more.
I am reverting this for now until I have time to sit down and implement this correctly and verify that it works as expected in all cases.
=> [Button] Revert the button tint color change.

components/Buttons/examples/ButtonsDynamicTypeViewController.swift, components/Buttons/src/MDCButton.h, components/Buttons/src/MDCButton.m, components/Buttons/tests/unit/ButtonsTests.m
This adds automatic font adjustment / Dynamic Type support to MDCButton.
The main functionality is exposed through the mdc_adjustsFontForContentSizeCategory property.
This property is modeled after the adjustsFontForContentSizeCategory property in the UIConnectSizeCategoryAdjusting protocol added by Apple in iOS 10.0.
=> [Button] Add Dynamic Type support

components/Snackbar/src/MDCSnackbarManager.h
In SDK, it is UIKit.framework/Versions/C/Headers/UIKit.h
Let me make the code use the same case so that it would be compiled on case sensitive filesystem.
=> [Snackbar] fix case of UIKit.h in MDCSnackbarManager.h

components/Typography/src/UIFont+MaterialTypography.m
If you attempt to use [UIFont mdc_preferredFontForMaterialTextStyle] with a non standard font loader we will NSLog a warning.
UIFontDescriptor will not generate a log message as one might wish to use those metrics with a custom font.
=> [Typography] Add warning about custom fonts and Dynamic Type
